purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5150376
  brandStrength: 0.2177113997749984
  lightness: 0.2424812
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  rhythmicContrast: 0.7531328
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: DangerousDolly
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7569124314468354
layout_spectrum: 0.741228
